### ISSUE TITLE
我个人的英语学习方案

### ISSUE THREAD

**Issue by ProudBenzene** [PKM-er/Pkmer-Docs#102]
有一篇介绍我个人英语学习方案的文章，涉及到英语学习思路、Projects插件、Note Synchronizer插件和Language Learner插件的部分使用方法及使用示例等。附大纲：

<img width="786" alt="image" src="https://github.com/PKM-er/Pkmer-Docs/assets/93238080/d2863a8b-c4cd-43d3-9954-a247c1728f94">

**Comment by windily-cloud** [comment]
非常感谢您的贡献，您这篇文章属于工作流的分享，肯定能帮助到很多人，可以pr，也可以直接发到这个issue里。

**Comment by ProudBenzene** [comment]
你好，我想自己pr，但是我之前几乎没有pr过，说明文档我看懂了，就是一个问题，请问文中的图片应该如何处理呢？

**Comment by windily-cloud** [comment]
图片可以直接在obsidian粘贴，会贴到Resource/images文件夹。当你pr后，我们会将其传到图床，用于网站展示，并删除文件夹中的图片。

**Comment by juestchaos** [comment]
非常支持，你图的图床问题，提交PR后，本地 Resource/images文件夹 内容，我们回来处理
