### ISSUE TITLE
评估一下是否值得开发obsidian 插件，接入全平台多内核浏览器的收藏夹同步开源项目：floccus.org

### ISSUE THREAD

**Issue by aiyou9** [PKM-er/Pkmer-Docs#106]
推荐关注一下自定义部署，支持webdav等同步方式，多平台，多内核浏览器， 同步收藏夹的开源项目  [ floccus ](https://github.com/search?q=+floccus&type=repositories)
是否能开发obsidian插件，接入它。
官网 https://floccus.org/
github搜索显示，支持本地，有windows和macos客户端：https://github.com/TCB13/LoFloccus
https://github.com/search?q=+floccus&type=repositories

**Comment by windily-cloud** [comment]
这都快一年没维护了，在易用性上不如raindrop，还带高亮，还开源，还能白嫖。在自部署上不如linkding，单docker就能部署，你这个还得开个webdev服务。

我自己就尝试过这种方法，之前就是nextcloud + floccus，不知道你是什么感受

**Comment by aiyou9** [comment]
> 这都快一年没维护了，在易用性上不如raindrop，还带高亮，还开源，还能白嫖。在自部署上不如linkding，单docker就能部署，你这个还得开个webdev服务。
> 
> 我自己就尝试过这种方法，之前就是nextcloud + floccus，不知道你是什么感受

我是用floccus + 日本的免费webdav：teraCloud ，确实功能单一点，要有稍后读，带高亮，有一个 omnivore.app
，ob有接入的插件
