### ISSUE TITLE
添加tiddlywiki和TidGi作为知识管理工具

### ISSUE THREAD

**Issue by dongrentianyu** [PKM-er/Pkmer-Docs#118]
TiddlyWiki 是丰富的、交互式的工具，用于处理复杂的数据，不易融入如试算表或文字处理的传统工具的结构。

TiddlyWiki 旨在适应围绕您的大脑，帮助您处理不合适的事情。基本的理念是更有用的、可重复使用信息，如果我们把它切成语义上有意义的片段 -- 条目 -- 并赋予标题，以便他们可以用链接、标签、清单和宏等方式结构化信息。条目使用 WikiText 标记，简明地表示广泛的文本格式和超文本特性。

TiddlyWiki 旨在为处理条目提供流体接口，允许其聚合组成更长的故事。

以上是tiddlywiki中文文档里的介绍，国内翻译成太微。tiddlywiki是一个和obsidian完全不同的笔记软件，当然在实现具体的笔记流程上会有交叉之处。

而tidgi则是国内开发者做的桌面版。可运行多个wiki。具体介绍见https://github.com/tiddly-gittly/TidGi-Desktop

**Comment by windily-cloud** [comment]
可以，非常欢迎。可以先提交文档看看放哪个位置比较好。

**Comment by dongrentianyu** [comment]
暂时先关闭吧。
