### ISSUE TITLE
在tiddlywiki里使用挂件会出错

### ISSUE THREAD

**Issue by dongrentianyu** [PKM-er/Pkmer-Docs#119]
![image](https://github.com/PKM-er/Pkmer-Docs/assets/109711900/15467fc5-58fe-4781-80e9-0c8c23192478)

如图，因为传入的html文档，结果内容就显示在head上面了，然后就显示在条目的标题里，而不是在正文中，感觉需要适配一下，或者有什么更好的css调整方案。

**Comment by windily-cloud** [comment]
这玩意儿开发压力有点大，暂时先搁置了，等文档能稳定产出了，再考虑适配各笔记软件，不然用户体验太差。现在挂件入口已关闭

**Comment by dongrentianyu** [comment]
后检查发现是我的字体设置比一般的要大，导致出现的问题。应该可以关闭issue了，反正就是调整里面的数值来适配。
