### ISSUE TITLE
Fast Image Cleaner插件介绍页面链接指向错了

### ISSUE THREAD

**Issue by martinniee** [PKM-er/Pkmer-Docs#150]
你好，我是 Fast Image Cleaner 插件开发者，最近关注到这个 社区及网站。发现
 这篇[文章](https://pkmer.cn/Pkmer-Docs/10-obsidian/obsidian%E7%A4%BE%E5%8C%BA%E6%8F%92%E4%BB%B6/nl-fast-image-cleaner/#%E5%88%A0%E9%99%A4%E9%99%84%E4%BB%B6%E5%8F%8A%E9%93%BE%E6%8E%A5 
)这个地方链接指向错了。
![image](https://github.com/PKM-er/Pkmer-Docs/assets/55736512/718d930b-22d1-4f19-aeb1-98dd5e737c2d)

**Comment by juestchaos** [comment]
已修复
