### ISSUE TITLE
关于表格单元格的嵌入问题

### ISSUE THREAD

**Issue by Heckler-Dark** [PKM-er/Pkmer-Docs#193]
问题现象：
当我们在OB的表格单元格「Table cell」里嵌入内容（笔记文本，内部链接），且同时需要为该嵌入项重命名时，会遇到无法正常显示的情况；
提示：这种显示有误的情况同时发生在【编辑】和【预览】两种模式下。
ps：只有在编辑模式下，且当鼠标的光标“竖线”位于表格内部时，嵌入链接的名称才显示正常，但这无异于是“掩耳盗铃”。

解决方案：
这时，我们需要在间隔符“|”（位于键盘上中括号右侧）前面添加反斜杠“\” ，便可消除显示有误的问题（举例如下）；
有误：[[ XX/YY/ZZ | 自定义名称 ]]
修正：[[ XX/YY/ZZ \ | 自定义名称 ]]

情况补充：
1.建议在为链接重命名时，提前预设好路径，且越详细越好，以免在后续的笔记编辑中出现意外；
即：能[[ XX/YY/ZZ \ | 自定义名称 ]]，就不要[[ XX/YY \ | 自定义名称 ]]。
2.使用上述的修正方案，虽然的确可以解决表格内嵌入的显示问题，但是当我们使用表格插件（Markdown Table Editor）时，又会产生新的问题——在Markdown Table Editor产生的表格副页里，链接的重命名可能会导致单元格的内容发生左右位移。
ps：虽然这不影响正常情况下的显示效果，但还是建议不要在Markdown Table Editor里进行链接的重命名操作，只用来生成初始表格即可。
3.经测试，该方法同样适合在简单的表格内，展开简短的文本段落。

**Comment by windily-cloud** [comment]
这是建议我们把表格的这种情况写进文档里吗？

**Comment by Heckler-Dark** [comment]
可以当成一种trick，本质是为了表格的正常显示。
一开始我是做了一个表格，并为每一个单元格嵌入了链接；
结果发现表格显示异常，后来找到了这个抵消错误的方案。
出错的原因应该是：OB在渲染时，把用来重命名的间隔符“|”当成了表格的间隔符，而用反斜杠“\”即可抵消这种渲染错误。

**Comment by windily-cloud** [comment]
可以，会加到文档中的，这个其实是标准markdown处理的方式

**Comment by windily-cloud** [comment]
@Heckler-Dark 已在最新版文档中添加
