### ISSUE TITLE
Obsidian中Excalidraw白板小技巧【1】 

### ISSUE THREAD

**Issue by PencilMing** [PKM-er/Pkmer-Docs#248]
本技巧是对下方链接文章中提到的嵌入部分的图文补充说明。
https://pkmer.cn/Pkmer-Docs/10-obsidian/obsidian%E7%A4%BE%E5%8C%BA%E6%8F%92%E4%BB%B6/obsidian-excalidraw-plugin/
## 如何在把Excalidraw的局部内容嵌入到obsidian中。
1. 首先确认你选择的部分是group（打组）的状态。
> <img width="279" alt="CleanShot UsersmingDocumentsMingObsidian小明基础插件库Excalidraw日记具体的需求 md-20230704-48@2x" src="https://github.com/PKM-er/Pkmer-Docs/assets/82462283/b1434fb0-5f6d-4a08-b3b7-8136813b4807">
如果不是group状态的话右键选择group selection。
> ![CleanShot UsersmingDocumentsMingObsidian小明基础插件库Excalidraw日记具体的需求 md-20230704-13@2x](https://github.com/PKM-er/Pkmer-Docs/assets/82462283/8e302ec3-6354-451d-8a48-2f2bff316474)
2. 选中你想要展示的group点击这个创建链接功能。
> ![CleanShot UsersmingDocumentsMingObsidian小明基础插件库Excalidraw日记具体的需求 md-20230704-51@2x](https://github.com/PKM-er/Pkmer-Docs/assets/82462283/94fc5f28-dcf6-4cf0-8e3d-4c868107ce9b)
3. 填入这个链接引用的名称并且选择Group或者Area。
> ![CleanShot UsersmingDocumentsMingObsidian小明基础插件库Excalidraw日记具体的需求 md-20230704-22@2x](https://github.com/PKM-er/Pkmer-Docs/assets/82462283/3f4b36ff-6c7f-4f23-a0bf-ba300932cf7d)
4.完成以后会自动复制这个链接，然后你就可以直接粘贴到你的笔记中。**完成！**
> <img width="896" alt="CleanShot UsersmingDocumentsMingObsidian小明基础插件库10 - 日志记录01 每日日志20232023年07月04日 md-20230704-41@2x" src="https://github.com/PKM-er/Pkmer-Docs/assets/82462283/9ae7e208-70aa-4aeb-bf3e-d77f3584794b">
可以通过嵌入链接的后方添加“｜+数字”来控制嵌入图片的宽度
> ![CleanShot UsersmingDocumentsMingObsidian小明基础插件库10 - 日志记录01 每日日志20232023年07月04日 md-20230704-03@2x](https://github.com/PKM-er/Pkmer-Docs/assets/82462283/7d4faeba-bdcd-45ff-9533-74c11f2b1004)

**Comment by juestchaos** [comment]
同意，我甚至觉得可以
单独针对 Excalidraw 写一批脚本的文章

**Comment by windily-cloud** [comment]
已添加 @PencilMing
