### ISSUE TITLE
pkmer网站使用体验

### ISSUE THREAD

**Issue by Hope2KZ** [PKM-er/Pkmer-Docs#254]
网站搜索功能 太鸡肋了 
资料教程很多 但就是这个搜索毁了一切
希望优化一下

**Comment by windily-cloud** [comment]
能具体说说吗，我这搜索是正常的

<img width="1051" alt="image" src="https://github.com/PKM-er/Pkmer-Docs/assets/30640638/8d96d91e-69d7-4b96-8abe-c4aa15a7d8b6">

**Comment by Hope2KZ** [comment]
![ID%~KHUJ1WHILE1JP $M7_J](https://github.com/PKM-er/Pkmer-Docs/assets/46066926/a6cd7c65-d78e-48f6-a703-4bfd164233f1)

**Comment by windily-cloud** [comment]
标题是不纳入搜索的，只搜索内容，后续会优化一下
