### ISSUE TITLE
《Obsidian 笔记基本查找》 可以添加检索的布尔运算以及一些实战

### ISSUE THREAD

**Issue by PandaNocturne** [PKM-er/Pkmer-Docs#255]
![0257d90ba1766c57acb9c4f4753fffd](https://github.com/PKM-er/Pkmer-Docs/assets/84729049/bef47257-8408-417e-8947-f0b8fee8038d)

**Comment by PandaNocturne** [comment]
针对下方链接《Obsidian 笔记基本查找》的文章，对全局搜索进行一定的		补充：
[Obsidian 笔记基本查找 (pkmer.cn)](https://pkmer.cn/Pkmer-Docs/50-%E6%95%99%E7%A8%8B/obsidian/obsidian-%E7%AC%94%E8%AE%B0%E5%9F%BA%E6%9C%AC%E6%9F%A5%E6%89%BE/)

### 检索方式

Obsidian的全局搜索的检索方式可以运用 **布尔逻辑运算符** 进行一定的 **模糊检索** 和 **精确检索**：
在检索之前可以把 **说明搜索含义** 的选项打开
![image](https://github.com/PKM-er/Pkmer-Docs/assets/84729049/f96dc1e5-1a4f-4c5d-b41f-382aaaabd54f)
> 注：用括号  `()`  可以把检索的内容给组合起来

- 模糊检索：
	- 或运算 `OR` ：
		- eg：`file:(笔记 OR obsidian .md)`
		- ![image](https://github.com/PKM-er/Pkmer-Docs/assets/84729049/2da6556d-4a2a-4b08-aadf-11b721ac547c)
		- 说明：检索文件名包含`笔记`**或者**`obsidian`的文件
- 精确检索：
	- 并运算 `空格` ：
		- eg：`file:(学习 笔记)`
		- ![image](https://github.com/PKM-er/Pkmer-Docs/assets/84729049/f6c127f3-e7e3-4126-94f9-2cb1193c8e85)
		- 说明：检索文件名包含`笔记`**和**`学习`的文件
	- 非运算 `-` ：
		- eg： `file:(笔记 - .png)`
		- ![image](https://github.com/PKM-er/Pkmer-Docs/assets/84729049/dcce6fc5-f726-4bf4-af2c-f5cf92180a8a)
		- 说明：检索文件名包含`笔记`的文件，但不包含`.png`的图片

**Comment by juestchaos** [comment]
well done

**Comment by windily-cloud** [comment]
已添加
