### ISSUE TITLE
学习julia中文社区的经验 https://discourse.juliacn.com/

### ISSUE THREAD

**Issue by aiyou9** [PKM-er/Pkmer-Docs#292]
# 举办培训计划

# 论坛有学科相关的类别

# 英文文档的翻译工作
Julia 语言相关的本地化工作，使用 [Transifex](https://www.transifex.com/) 作为协助翻译平台 **此平台可以联系平台客服，评估开源项目，免费使用** 。对有意参与翻译工作的人员，提供了详细的[翻译指南](https://discourse.juliacn.com/t/topic/277)

## Julia 技术翻译计划 —— 征集与赞助

1. 讨论了翻译工作的机制
https://discourse.juliacn.com/t/topic/6810

2. 提供了julia版本，调用谷歌翻译api，处理md文件
https://github.com/RexWzh/GoogleTranslates.jl

3. 【中文文档】Transifex已死，ChatGPT永生
提供了一个示例的中文排版要求的prompt
https://discourse.juliacn.com/t/topic/7054/2

# （代理？）官方周边商店
主要是带logo皮肤的衣服，帽子，口罩，和盒子，茶杯，感觉还不错
https://shop.spreadshirt.com/numfocus/official+julia+logo?idea=5bca3ad9f93764414a5de55f

# 提供包安装的镜像站
https://discourse.juliacn.com/t/topic/2969

# 翻译国外著作
https://cn.julialang.org/JuliaDataScience/

**Comment by windily-cloud** [comment]
用GPT总结了一下，主要是以下几个关键点：

1. 举办培训计划
2. 论坛有学科相关的类别
3. 英文文档的翻译工作
4. Julia语言相关的本地化工作，使用Transifex作为协助翻译平台
5. 提供Julia技术翻译计划，并征集与赞助
6. 提供带logo皮肤的衣服、帽子、口罩等官方周边商品
7. 提供包安装的镜像站
8. 翻译国外著作

目前的境况：能一起为爱发电干这些事的人少，文档的主要贡献者不足五个，文档除了解决协作者的PR，issue，沟通回复，还涉及到文档组织，网站开发等比较繁重。我们除了文档，还有ob和zotero插件，前后端开发这块也耗去了绝大部分开发精力，得等到基础设施完善后才能分出精力。

针对上述内容一一回复：

1. 培训：缺人，缺时间，缺精力，且效果可能达不到预期
2. 有学科类别，但并没有强调出来
3. 优秀英文文档翻译涉及到如何确定是优秀的英文文档，又由谁来翻译的问题，这里需要有人带领组织
4. ob的本地化已经很好了，我们pr了大量的插件翻译，目前需要的依然是需要有人付出精力
5. 同上
6. 这个还非常早，多干实事，没精力捣鼓实体商品
7. 这个已经有了，还在内测。不仅有ob插件，未来还将把zotero插件的镜像安装服务也安排上
8. 还是翻译问题

主要问题集中在，我们缺人，缺会组织，能组织的人才帮我们一起干这些事。如果你有意愿，我觉得你可以试试。

**Comment by aiyou9** [comment]
翻译国外著作，这个可以搞，可以和用obsidian的单词学习，英语学习联系起来，我记得pkmer有大佬ob，构建的单词库授权

# 优秀语料来源
https://www.gutenberg.org/ 
我在古腾堡开源图书计划中，看到一本好书，
Title: A Treatise Concerning the Principles of Human Knowledge
https://www.gutenberg.org/files/4723/4723-h/4723-h.htm

但是需要大家评价，吸引更多人加入。还有古腾堡计划中开源书，进行翻译，二次发布，是否有版权问题，看说明，好像在美国地区，没有问题，github在美国地区。

# 单词库

史上最强大的英语近义词词典与Obsidian软件联合军演
 https://www.bilibili.com/video/BV1as4y1b762

# 将单词与文章中进行关联的处理方法

使用obsidian制作并维护个人专有知识库
https://www.bilibili.com/video/BV1UP4y1b74L

# 运营方式

以《A Treatise Concerning the Principles of Human Knowledge》为例
可以用沉浸式翻译，处理一个中英文对照的机器翻译的版本，

然后使用支持个人专业知识库方式，把书与近义词词典库中单词，进行关联，可以在obsidian中进行 标注上单词的学习，同时可以扩充，提交到词典库，以上都是github来管理版本，

然后每一段英文原文，后面加评论，可以用obsidian中插件来处理，比如reading-comment评论插件（评论有大纲），可以一键折叠其他成员的翻译版本，或者给出一个翻译的标志词，和个人针对某句话化的发表的观点。

每个人写的内容使用 @github用户名，来区分。

防止合并有冲突，约定一些规则，减少解决冲突的可能，比如obsidian的插件，只会增加内同，不会改动别人的内容（还是个想法，没找到这种插件）

**Comment by aiyou9** [comment]
另一个开源wiki翻译平台   https://translatewiki.net/

**Comment by aiyou9** [comment]
这些还是你们自己商定，先关闭了
