### ISSUE TITLE
抓取插件 Readme 时，若 repo 包含中文 Readme，能否识别并直接获取？

### ISSUE THREAD

**Issue by Acylation** [PKM-er/Pkmer-Docs#363]
感谢这个站点，是一个很好的面向国内用户发布信息的平台，也帮助开发者做了些推广

我注意到上周这个网站更新了官方市场插件的 Readme 文档。有些插件已经提供了中文的文档，能不能直接抓取呢，跟机翻的感觉还是不一样

**Comment by juestchaos** [comment]
这个需求很很厉，也希望更多开发者能够聚集在一起
有几个实现的难点
- 很难了解全面每个插件的是否有中文教程，这个是个逐步对插件认知的过程，不太可能多1000多插件如数家珍
- 有些插件可能有中文文档，但是默认显示的是中文，抓取策略没有考虑到，而且可能并不多

比如像  [obsidian-chem](https://github.com/Acylation/obsidian-chem/tree/main) 
插件就很好，我其实鼓励提交一份 介绍和活用放到社区

**Comment by Acylation** [comment]
> 很难了解全面每个插件的是否有中文教程
> 有些插件可能有中文文档，但是默认显示的是中文，抓取策略没有考虑到

PKMer 有个 awesome list 记录了这个，虽然可能不全面，但是可以先把已知的这些搬运一下，不过确实更新起来挺累的 https://github.com/PKM-er/awesome-obsidian-zh

> 比如像 [obsidian-chem](https://github.com/Acylation/obsidian-chem/tree/main) 插件就很好，我其实鼓励提交一份 介绍和活用放到社区

嗯最近正在准备文档，写好了在这里也发一份
