### ISSUE TITLE
请求添加obsidian-modular-css-layout的css的介绍

### ISSUE THREAD

**Issue by PandaNocturne** [PKM-er/Pkmer-Docs#393]
对于 [Obsidian 能像其他笔记样分栏嘛]( https://pkmer.cn/show/20230603163007 ) 提及到分栏链接，已经更换为了插件。
对此，我想介绍另一个分栏css：https://github.com/efemkay/obsidian-modular-css-layout，相比较而言更加方便和使用，样式也比较丰富。

申请对该CSS样式进行翻译介绍，估计需要一些篇幅。

**Comment by windily-cloud** [comment]
你已经是个合格的大佬了，如果你看到网站没有，可以直接PR的😘

**Comment by windily-cloud** [comment]
我明天统一进行合并

**Comment by PandaNocturne** [comment]
好滴 我就低级的搬运工😂
