### ISSUE TITLE
汉化插件

### ISSUE THREAD

**Issue by jdjshhc** [PKM-er/Pkmer-Docs#401]
- 插件汉化教程
- 汉化好的插件
- 一键可以汉化的插件

**Comment by juestchaos** [comment]
这个问题，在 各个群里，都跟大家提过，也讨论过

目前为止存在一个讨论点
大家是因为不懂因为才不会用插件？还是因为插件本身各自设置不同?

**Comment by jdjshhc** [comment]
- 这两种应该都是有的
- 对于我来说，是看英文不太懂，用起来麻烦，本身设置的话就没问题。

**Comment by juestchaos** [comment]
所以社区通过协作方式，还有 AI 翻译，做了 插件使用的文档
