### ISSUE TITLE
键盘使用指南

### ISSUE THREAD

**Issue by Immortal-Sty** [PKM-er/Pkmer-Docs#413]
我想写一个键盘使用指南，给电脑小白看的，主要介绍键盘编辑区各键的功能。

**Comment by windily-cloud** [comment]
可以啊，这样咱可以开硬件专区了🤗

**Comment by Immortal-Sty** [comment]
请问我是该把它放到哪个分类里面呢？是新建一个还是放在现有的里面啊？

**Comment by windily-cloud** [comment]
> 请问我是该把它放到哪个分类里面呢？是新建一个还是放在现有的里面啊？

先放其它里吧，等内容足够多，我们可以搞个专题，就像obsidian和zotero一样

> 另外，我想把 Callout 放到 Quickadd 里面，可以吗？[这个](https://github.com/Immortal-Sty/Obsidian-ceShi)是我测试用的库，我的 Quickadd 数据也在里面，你可以看看。

不建议放这个。因为公用的库需要尽可能保持精简，每个人习惯不一样。我在 latex-suite 里定制了callout的写法，估计很少掉人会去用。我用quickadd搞了个git push操作，也没见到人用，都是用VSCode进行git操作。看看后续需不需要去掉。建议还是在自己库里写好了直接放 Pkmer-Docs 。这个问题其实可以开个disccuss 讨论一下。
