### ISSUE TITLE
[BUG] 网站有一些小 bug

### ISSUE THREAD

**Issue by Immortal-Sty** [PKM-er/Pkmer-Docs#422]
## Callout 语法支持有问题

这是原码：

```markdown
> ![Info]-
> 
> 好吧，其实选中全文直接按 `Ctrl+A` 就好了……
```

这是网站显示的：

![](https://raw.githubusercontent.com/Immortal-Sty/imgBed/master/PicGo/202309071100697.png?token=AWP2C6JPBTEASVANLURZ3TDE7E6QK)

## 脚注语法支持有问题

它的显示并没有问题，问题在于跳转。

我在正文中点击脚注数字上标时，会正常地自动跳转到文末的脚注位置，但我在文末脚注位置点击返回的跳转按钮，它直接跳转到文章最开头了。

**Comment by windily-cloud** [comment]
哦，不好意思，当时合并时没注意到不支持这个callout。脚注是已知问题，一直没来得及修，预计本周看能不能抽空修了。

**Comment by PandaNocturne** [comment]
我也顺带提个Bug，高亮好像并没有渲染
![image](https://github.com/PKM-er/Pkmer-Docs/assets/84729049/74744af8-4019-419e-a5df-c32362272e19)

**Comment by windily-cloud** [comment]
这些已经修复了吧
