### ISSUE TITLE
网站能否获取到其他仓库里的markdown文件？

### ISSUE THREAD

**Issue by dongrentianyu** [PKM-er/Pkmer-Docs#473]
我预计使用Docusaurus框架，用markdown的形式，按照常见的教程形式，写一个相对比较完整初级入门的tiddlywiki教程。到时不知道网站能不能获取github仓库里的markdown文件？

**Comment by windily-cloud** [comment]
理论上是能的，但是上传到网站上的md文件有一套规范，比如：

- 必须有规定的yaml
- 尽量不能包含非开源的东西，付费的推广等，因为这有广告嫌疑
- 格式只能是网站支持的md语法，尽量用双链链接

这些在ob库里都有自动化工具，如果读取其它仓库，格式不容易满足不说，也不可控。pkmer网站是备案了的，有问题都是我们负责。所以这个建议应该不会采纳，望理解。

**Comment by dongrentianyu** [comment]
pr主要是不能及时更新，总不能我写完一次pr一次。不过你说的也对，这些还是看未来发展吧。

**Comment by dongrentianyu** [comment]
我也不好说，反正我先写。仓库也建好了。https://github.com/dongrentianyu/the-handbook-of-tiddlywiki

对应的在线网址也部署好了。https://dongrentianyu.github.io/the-handbook-of-tiddlywiki/

我主要是觉得如果pkmer能够获取到这个仓库里的内容，可以在网站上加载出来的话，就可以让国内用户更快访问。

而这个Docusaurus扩展性还挺强的，虽然我不太会用到markdown的复杂功能，但也不一定，因为也有为了阅读体验的需要。

最终教程成型了，你们可以克隆一份放到你们网站上。但里面格式问题，就需要你们改了。

反正现在都不太确定，因为我还没正式动手写。也有可能我会加入付费内容，也有可能我写一半就不写了。都不确定的。只能说是看后面怎么操作吧。

而且如果只能读取ob库形式的markdown，感觉也很受限制。

**Comment by windily-cloud** [comment]
所以等确定了再说吧，目前在已有的td主题页上写上你这个教程链接就好了。我们这开发压力也挺大的，还是能不动就不动。
