### ISSUE TITLE
网页404

### ISSUE THREAD

**Issue by Twenru-zzh** [PKM-er/Pkmer-Docs#530]
https://pkmer.cn/Pkmer-Docs/10-obsidian/obsidian%E4%BD%BF%E7%94%A8%E6%8A%80%E5%B7%A7/obsidian_2023_seyee/#:~:text=%E5%8F%AB%E6%90%9C%E7%B4%A2%E5%AD%98%E6%A1%A3%E3%80%82-,%E6%9C%80%E5%90%8E,-%E6%88%91%E7%9A%84%20obsidian%202023
这个链接的文章出链能点出去，但是入链点不回来

https://pkmer.cn/Pkmer-Docs/10-obsidian/obsidian%E4%BD%BF%E7%94%A8%E6%8A%80%E5%B7%A7/obsidian%E4%BD%BF%E7%94%A8%E6%8A%80%E5%B7%A7/#:~:text=%E7%94%A8%20Obsidian%20%E4%B8%A4%E5%B9%B4%E5%A4%9A%EF%BC%8C%E7%8E%B0%E5%9C%A8%E6%88%91%E6%80%8E%E4%B9%88%E5%90%8C%E6%AD%A5%E5%92%8C%E4%BD%BF%E7%94%A8

https://pkmer.cn/Pkmer-Docs/10-obsidian/obsidian/#%E7%BB%8F%E9%AA%8C%E5%88%86%E4%BA%AB:~:text=%E5%AE%9E%E8%B7%B5%20by%20alswl-,Obsidian_2023_seyee,-%EF%BC%9A%E7%94%A8%20Obsidian%20%E4%B8%A4

**Comment by windily-cloud** [comment]
记录了，下次更新会改

**Comment by juestchaos** [comment]
已经修复
