### ISSUE TITLE
希望认领插件

### ISSUE THREAD

**Issue by HoBeedzc** [PKM-er/Pkmer-Docs#538]
我是一名 obsidian 的插件开发者，近期了解到了 PMKer，并且注册了账号，发现在网站上可以搜索到我开发的插件，想问一下网站目前可以认领自己的插件吗

**Comment by windily-cloud** [comment]
参与贡献是吧，非常欢迎呀！有啥需要帮忙的吗？

**Comment by juestchaos** [comment]
欢迎啊，有作者自己来写非常好

**Comment by juestchaos** [comment]
请问文章和内容准备的如何了？
