### ISSUE TITLE
投稿-搭建基于Azure OpenAI的自用ChatGPT

### ISSUE THREAD

**Issue by no251-1** [PKM-er/Pkmer-Docs#548]
国内访问OpenAI总是存在诸多阻碍，充值或者拼车使用也经常翻车，远不如Azure OpenAI稳定。Azure，也就是微软的云服务，可以用docker镜像生成web app，非常方便。Azure OpenAI也有GPT3.5、GPT4等模型。

### 第一步 注册Azure账号

https://azure.microsoft.com/zh-cn/free/

### 第二步 申请Azure OpenAI

https://zhuanlan.zhihu.com/p/614242045

注意，Azure OpenAI申请通过后就可以用GPT3.5 Turbo、GPT3.5 16K等模型了。而GPT4则需要单独申请，一般3-5天就能通过。

### 第三步 创建Web应用

首先，在应用程序服务中创建一个Web应用。

![image](https://github.com/PKM-er/Pkmer-Docs/assets/36976375/9749c016-b7b5-468d-9499-63800ceea3b8)

然后，在创建Web应用界面选择*订阅*和*资源组*。通常新注册的账号只有一个*订阅*，资源组则需要新建一个。Web应用名称即未来使用的网址，具有唯一性。比如，应用名称为xxx，网址即为 xxx.azurewebsites.net。*发布*选Docker容器，*操作系统*选Linux，*区域*可以选East Asia。*定价计划*选免费 F1就可以，足够用。如果是新注册的账号，微软会赠送100美元，可以选一个贵一点的，因为赠送的100美元一个月后就过期了。

![image](https://github.com/PKM-er/Pkmer-Docs/assets/36976375/34108ee7-fd08-4c09-996f-ab861c710afd)

在最上面一排的菜单里选*Docker*，*映像源*选Docker Hub，*映像和标记*为：yidadaa/chatgpt-next-web。

### 第四步 配置Web应用

Web应用创建好之后，我们需要设置一些环境变量。先在主页选择刚建好的Web应用。在左侧菜单中选择配置。在配置中添加几个新应用程序设置。

|名称|值|备注|
|:-:|:-:|:-:|
|PORT|433||
|OPENAI_API_KEY|sk-xxx|如果用OpenAI的Key，可以在这里输入|
|CODE|登录密码|可以设置多个密码，如password1,password2|
|AZURE_API_KEY|Azure OpenAI的秘钥|在已创建的Azure OpenAI中查看|
|AZURE_API_VERSION|API版本|在已创建的Azure OpenAI中查看|
|AZURE_URL|https://xxx.openai.azure.com/openai/deployments/name|xxx为终结点，name为Azure OpenAI中的部署名|

AZURE_API_KEY、AZURE_API_VERSION、AZURE_URL这几个参数的位置比较难找，而且需要自己组合。可以参考以下的截图。

![image](https://github.com/PKM-er/Pkmer-Docs/assets/36976375/db85b00b-f928-4d4e-b53f-faa396aa8d26)

秘钥和终结点。

![image](https://github.com/PKM-er/Pkmer-Docs/assets/36976375/04286179-a268-4a58-8b78-6c473eea9aa7)

JSON视图中可以找到API版本。

![image](https://github.com/PKM-er/Pkmer-Docs/assets/36976375/5b029290-51fb-4c26-a821-765eec73c126)

转到Azure OpenAI Studio可以查看模型和部署模型。模型部署后可以在部署菜单里找到部署名。

### 第五步 使用

属于你自己的ChatGPT已经搭建好了，通过xxx.azurewebsites.net即可访问。由于是Web应用，手机、电脑都可以用哦。

![image](https://github.com/PKM-er/Pkmer-Docs/assets/36976375/6e4b62dd-24d0-465b-9028-7909d029cd66)

Web应用运行界面。

### 附录

1. [Azure OpenAI 服务定价](https://azure.microsoft.com/zh-cn/pricing/details/cognitive-services/openai-service/)
2. [ChatGPT Web App搭建](https://edi.wang/post/2023/5/18/deploy-chatgpt-next-web-to-azure-app-service-with-individual-account-login-in-3-minutes)

**Comment by no251-1** [comment]
笔名一刀，多谢大家。

**Comment by windily-cloud** [comment]
好的，谢谢一刀老师的贡献，那我把之前的那篇也统一为一刀吧
