### ISSUE TITLE
之前请皮佬，提交的colored-tags-wrangler插件的GitHub项目与配置选项的翻译稿，没有看到，请帮忙检查一下，贡献者：山人

### ISSUE THREAD

**Issue by aiyou9** [PKM-er/Pkmer-Docs#579]
在这里看到这个插件的github项目的readme文件翻译
https://pkmer.cn/Pkmer-Docs/10-obsidian/obsidian%E7%A4%BE%E5%8C%BA%E6%8F%92%E4%BB%B6/readme/colored-tags-wrangler_readme/

没找到我提交的

贡献者： 山人

**Comment by windily-cloud** [comment]
@juestchaos 之前给叔发了，麻烦他检查下

**Comment by juestchaos** [comment]
花了点时间改完部署了
- 翻译，可以缩短下内容，和布局结构
- 标题可以采用中文优先，英文放在后面或者括号中
