### ISSUE TITLE
文章页面有bug，需要修改

### ISSUE THREAD

**Issue by aiyou9** [PKM-er/Pkmer-Docs#583]
![image](https://github.com/PKM-er/Pkmer-Docs/assets/15712822/ff6a1755-5b62-48ea-9249-b2c3a65b1ba6)
页面有bug https://pkmer.cn/Pkmer-Docs/10-obsidian/obsidian%E7%A4%BE%E5%8C%BA%E6%8F%92%E4%BB%B6/tasks-calendar-wrapper/

**Comment by juestchaos** [comment]
网络问题，你网络卡了，就会遇到这个
