### ISSUE TITLE
日期写错了

### ISSUE THREAD

**Issue by aiyou9** [PKM-er/Pkmer-Docs#607]
[日期写成2024年12月30日的页面](https://pkmer.cn/Pkmer-Docs/10-obsidian/obsidian%E7%A4%BE%E5%8C%BA%E5%91%A8%E6%8A%A5/2023-12-30-obsidianroundup/#2024-12-30the-new-obsidian-has-arrived)
![image](https://github.com/PKM-er/Pkmer-Docs/assets/15712822/595663fb-e9e0-4d1d-9732-700878d447da)

**Comment by juestchaos** [comment]
fix
