### ISSUE TITLE
部分图片丢失

### ISSUE THREAD

**Issue by SnowOwlet** [PKM-er/Pkmer-Docs#671]
链接：https://pkmer.cn/Pkmer-Docs/10-obsidian/obsidian%E7%A4%BE%E5%8C%BA%E6%8F%92%E4%BB%B6/readme/notion-like-tables_readme/

**Comment by SnowOwlet** [comment]
> 链接：https://pkmer.cn/Pkmer-Docs/10-obsidian/obsidian%E7%A4%BE%E5%8C%BA%E6%8F%92%E4%BB%B6/readme/notion-like-tables_readme/

补充 ![3301879025](https://github.com/PKM-er/Pkmer-Docs/assets/70618064/b5d5125d-7987-4690-98be-33cc347b15bd)

**Comment by cumany** [comment]
你好 这因为dataloom 原始readme更新已经删除了这些图片，稍后会同步新版的readme
