### ISSUE TITLE
I plan to write a document about compring between memos solutions and how to compensate for the Thino synchronization defects.

### ISSUE THREAD

**Issue by BabyXinORZ** [PKM-er/Pkmer-Docs#749]
Memos solutions include flomo, usememos and thino. Thino has irreplaceable advantages, but it also has some drawbacks on sync.

 I'd like to share my sync method, which would avoid file overwriting between PC and mobile phone.

**Comment by BabyXinORZ** [comment]
31eb703e65e33514090100fff0052f4497f182f9 commit 已提交

**Comment by juestchaos** [comment]
Good Job
Translate to English: "Add the author's name to the 'author' field in the document diligently."

**Comment by BabyXinORZ** [comment]
> Good Job Translate to English: "Add the author's name to the 'author' field in the document diligently."

Author information has been updated.
