### ISSUE TITLE
看着很棒啊，支持私有部署吗？

### ISSUE THREAD

**Issue by SadSock** [PKM-er/Pkmer-Docs#765]
感谢🙏

**Comment by windily-cloud** [comment]
请问您的需求是什么，为什么要私有部署文档，pkmer.cn 应该是能直接看的

**Comment by SadSock** [comment]
公司的内网里部署一个，公司的内网是访问不了外网的

**Comment by windily-cloud** [comment]
ob里也能查看内容，推荐clone下来在ob里查看，体验会更好

**Comment by juestchaos** [comment]
你可以自己使用这个文档用于学习，当请不要在社区不知情的情况下，将里面的内容用于商业化
