### ISSUE TITLE
【工作流分享】在Obsidian中做Toggl时间记录复盘

### ISSUE THREAD

**Issue by xychang** [PKM-er/Pkmer-Docs#768]
我最近实现了一个自用的工作流，简单整理了一个文档出来。想请问一下社区接不接受这样的投稿，以及有没有什么需要修改的方向。
[在Obsidian中做时间记录复盘.pdf](https://github.com/PKM-er/Pkmer-Docs/files/15211957/Obsidian.pdf)

**Comment by windily-cloud** [comment]
任何非政治、非广告、非营销、不违反国家法律法规等内容都能接受，文章里没有可以引导使用付费软件 toggl，符合要求。此外最好提供Markdown文档才能给出修改建议

**Comment by xychang** [comment]
建了一个pull request，方便的话请帮忙看看有没有什么需要修改的地方。

**Comment by juestchaos** [comment]
已经合并了
